# Generated by Django 4.0.4 on 2022-05-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_create_data_answer_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='subject',
            new_name='question',
        ),
    ]
