# Generated by Django 4.0.1 on 2022-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
